spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: my-test-project
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  #数据库连接
  datasource:
    #driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    driver-class-name:  com.mysql.cj.jdbc.Driver
    #数据库读写分离；读库端口：8066；写库端口：13306
    url: jdbc:mysql://mysql://localhost:3306/sys?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    # url: jdbc:p6spy:mysql://localhost:3306/sys?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
mybatis:
  #开启驼峰命名法
  configuration:
    map-underscore-to-camel-case: true
mybatis-plus:
  # xml地址
  mapper-locations: classpath:/mapper/**/*.xml
  # 实体扫描，多个package用逗号或者分号分隔
  #type-aliases-package: *   #自己的实体类地址
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8808
  servlet:
    context-path: /eddie
  tomcat:
    uri-encoding: UTF-8
